[tool.poetry]
name = "python"
version = "0.1.0"
description = ""
authors = ["fitzypop <fitzypop@pm.me>"]

[tool.poetry.dependencies]
python = "^3.10"
devtools = "^0.8.0"
pydantic = "^1.9.0"
bson = "^0.5.10"
Flask = "^2.0.3"
requests = "^2.27.1"
PySimpleGUI = "^4.57.0"
orjson = "^3.7.1"
SQLAlchemy = "^1.4.39"
aiohttp = "^3.8.3"
pytest = "^7.2.0"
pytest-asyncio = "^0.20.3"
asyncmock = "^0.4.2"

[tool.poetry.dev-dependencies]
black = "^22.1.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.237"
black = "^22.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
