[tool.poetry]
name = "python-repo"
version = "0.1.0"
description = ""
authors = ["fitzypop <fitzypop@pm.me>"]

[tool.poetry.dependencies]
python = "^3.10"
devtools = "^0.12"
pydantic = "^2"
bson = "^0.5.10"
requests = "^2.31.0"
PySimpleGUI = "^5"
orjson = "^3"
SQLAlchemy = "^1.4.39"
aiohttp = "^3"
pytest = "^8"
pytest-asyncio = "^0.23"
flask = "^3"
matplotlib = "^3"
psutil = "^5.9.8"
pydantic-settings = "^2.2.1"


[tool.poetry.group.dev.dependencies]
ruff = "^0.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
