[project]
name = "oauth_checker"
version = "0.1.0"
description = ""
authors = [{ name = "fitzypop", email = "fitzypop@pm.me" }]
requires-python = "~=3.10"
dependencies = ["requests>=2.32.0,<3", "orjson>=3.9.15,<4"]

[tool.pyright]
venvPath = "."
venv = ".venv"
