[project]
name = "pysimplegui_demo"
version = "0.1.0"
description = ""
authors = [{ name = "fitzypop", email = "fitzypop@pm.me" }]
requires-python = "~=3.10"
dependencies = ["PySimpleGUI>=5,<6"]

[dependency-groups]
dev = []

[tool.pyright]
venvPath = "."
venv = ".venv"
