[project]
name = "numpy-tut"
version = "0.1.0"
description = ""
authors = [{ name = "fitzypop", email = "fitzypop@pm.me" }]
requires-python = ">=3.9,<3.11"
dependencies = ["numpy>=1.26.0,<2"]


[tool.pyright]
venvPath = "."
venv = ".venv"
